# Generated by Django 3.2.3 on 2021-07-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categry',
            new_name='Category',
        ),
    ]
